# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rollmean <- function(x, k, na_pad = FALSE, na_rm = FALSE, align = "left") {
    .Call(`_cragr_rollmean`, x, k, na_pad, na_rm, align)
}

rollsum <- function(x, k, na_pad = FALSE, na_rm = FALSE, align = "left") {
    .Call(`_cragr_rollsum`, x, k, na_pad, na_rm, align)
}

